### ISSUE TITLE
make sink type an env variable

### ISSUE THREAD

**Issue by Eikix** [kkrt-labs/kakarot-indexer#9]
```[tasklist]
### Tasks
- [ ] make sink type an env variable
- [ ] add mongodb connection string env variable if mongo is the console type
- [ ] add in README
- [ ] add a .env.example
```
